# Generated by Django 3.1.7 on 2021-03-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_auto_20210301_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='animals'),
        ),
    ]
