# Generated by Django 3.1.7 on 2021-03-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_animal_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZooImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='zoo_img')),
            ],
        ),
    ]
